[package]
name = "mpi_test"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = { version = "2.0.58", features = ["full"] }

[dev-dependencies]
mpi = "0.7.0"
